# Generated by Django 3.1.1 on 2020-09-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
