# Generated by Django 3.1.1 on 2020-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_sterlized',
            field=models.BooleanField(default=False),
        ),
    ]
