# Generated by Django 3.1.1 on 2020-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_animal_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
