# Generated by Django 3.1.1 on 2020-09-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='animal.vet'),
            preserve_default=False,
        ),
    ]
