# Generated by Django 3.1.1 on 2020-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0009_auto_20200908_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='microchip',
            field=models.CharField(default='', max_length=26),
            preserve_default=False,
        ),
    ]
